services:
  php:
    build: .docker/php/.
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - '.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - '.:/var/www'
    links:
      - php